name: Test action v2

on:
  push:
    branches:
      - "v2.0.0"
jobs:
  TestV2:
    name: Test v2 action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: Test input
        with:
          filePattern: "README.md"
          params: |
            {
              "finds": [
                "secrets._a", 
                "secrets._b_"
              ],
              "replaces": [
                "val_1", 
                "${{secrets.HTS_TEST}}"
              ]
            }